version: '3'

services: 

  terraform-a:
    image: hashicorp/terraform:1.4
    entrypoint: sh
    env_file:
      - ./account_a/.env
    volumes:
      - ./account_a:/account_a
    working_dir: /account_a
    tty: true

  terraform-b:
    image: hashicorp/terraform:1.4
    entrypoint: sh
    env_file:
      - ./account_b/.env
    volumes:
      - ./account_b:/account_b
    working_dir: /account_b
    tty: true

  aws:
    image: amazon/aws-cli:latest
    entrypoint: sh
    volumes:
      - ./aws:/root/.aws
    tty: true
